version: 2

sources: 
  - name: snowflake_data_source
    description: "A snowflake db that hold source data"
    database: sales
    schema: public
    tables:
        - name: physical_stores
          description: "Descriptive data for physical shops"
          columns:
          - name: store_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                
        - name: store_sales
          description: "Sales data in raw unprocessed form"
          columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: user_id
            description: "The primary key for this table"
            tests:
                - not_null

        - name: store_shipments
          description: "Shipment data in raw unprocessed form"
          columns:
          - name: shipment_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

          - name: shipping_route
            description: "Route ID for the specific record"
            tests:
                - not_null