
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'data_tranforms'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'
vars: # variables to be used throughout the project
    best_county: 001
# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

#on-run-start: "{{ pre_ops(project_level }}"
#on-run-end: "SQL statement you wish to run after project models are run"

models:
  data_tranforms:
      pre-hook: "{{ pre_ops(model_level }}"
      post-hook: "SQL statement you wish to run after this  model is run"
      # Applies to all files under models/example/
      example:
          materialized: view

